[package]
name = "pinka"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
axum = "0.8.1"
fd-lock = "4.0.2"
fjall = "2.4"
futures = "0.3.31"
postcard = { version = "1.1.1", default-features = false, features = [
    "use-std",
] }
ractor = { version = "0.14.4", features = [
    "cluster",
], path = "../../ractor/ractor" }
ractor_cluster = { version = "0.14.4", path = "../../ractor/ractor_cluster" }
rand = "0.8.5"
rustls-pki-types = { version = "1.10.1", features = ["std"] }
rustls-platform-verifier = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.42", features = [
    "fs",
    "macros",
    "rt-multi-thread",
    "signal",
    "time",
] }
tokio-rustls = "0.26.1"
toml = "0.8.19"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
xflags = "0.3.2"
