[package]
name = "pinka"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
axum = "0.8.1"
fjall = "2.4"
ractor = { version = "0.14.2", features = ["cluster"] }
ractor_cluster = "0.14.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.42", features = [
    "process",
    "rt-multi-thread",
    "signal",
    "tokio-macros",
] }
toml = "0.8.19"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
