[package]
name = "pinka"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
axum = "0.8.1"
fjall = "2.4"
futures = "0.3.31"
postcard = { version = "1.1.1", default-features = false, features = [
    "use-std",
] }
ractor = { version = "0.14.3", features = ["cluster"] }
ractor_cluster = "0.14.3"
rand = "0.8.5"
rustls-pki-types = { version = "1.10.1", features = ["std"] }
rustls-platform-verifier = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.42", features = [
    "macros",
    "rt-multi-thread",
    "signal",
    "time",
] }
toml = "0.8.19"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
xflags = "0.3.2"
